### ISSUE TITLE
Will multiplayer be added?

### ISSUE THREAD

**Issue by mewhhaha** [magnusGU/swedishUniversities#1]
_Great project!_ I put this in my microwave and it worked splendidly. But I was sad to discover I couldn't play this project with my non-existent friends. Will I ever find love?

**Comment by magnusGU** [comment]
Great feedback valued user. I will get right on it, but for now use [https://tinder.com/](url) to relieve your most-pressing issue.

This along with VR-capabilities are our number one priority. #69

**Comment by mewhhaha** [comment]
I won't be shopping here again.
